cd 'c:\work\m'

mex -argcheck -g -O ...
-outdir ./class/packed/@packed/ -output mtimes ...
./class/packed/@packed/mtimes.c ./class/packed/@packed/private/mx2.c ...
'O:\Exefiles\MATLAB_R2007a\extern\lib\win32\lcc\libmwlapack.lib'
%'C:\Program Files\MATLAB\R2007a\extern\lib\win64\microsoft\libmwlapack.lib'

%mex -argcheck -g -O ...
%mtimes.c ./private/mx2.c ...
%'O:\Exefiles\MATLAB_R2007a\extern\lib\win32\lcc\libmwlapack.lib'
%%'C:\Program Files\MATLAB\R2007a\extern\lib\win64\microsoft\libmwlapack.lib'

mex -argcheck -g -O ...
-outdir ./class/packed/@packed/private/ -output call_lapack ...
./class/packed/@packed/private/call_lapack.c ./class/packed/@packed/private/mx2.c ...
'O:\Exefiles\MATLAB_R2007a\extern\lib\win32\lcc\libmwlapack.lib'
%'C:\Program Files\MATLAB\R2007a\extern\lib\win64\microsoft\libmwlapack.lib'

% need not to compile and link mx2 separately.
