addpath(genpath('c:\work\fx\frontal\'))

test('defrontal')
test('defrontal_flat')
test('defrontal_flat2')
test('defrontal_pt')
test('frontalfun')
test('frontal_blkdiag')
test('frontal_deflatten')
test('frontal_diag')
test('frontal_eye')
test('frontal_flatten')
test('frontal_inv')
test('frontal_mtimes')
test('frontal_mtimes2')
test('frontal_mtimes2_pt')
test('frontal_mtimes_pt')
test('frontal_mtimes_pt_rev')
test('frontal_propagate_cov')
test('frontal_pt')
test('frontal_reshape')
test('frontal_times')
test('frontal_transpose')
test('frontal_variance')
test('isfrontal')

%test('ctranspose', 'frontal')
%test('defrontal', 'frontal')
%test('diag', 'frontal')
%test('display', 'frontal')
%test('frontal', 'frontal')
%test('horzcat', 'frontal')
%test('inv', 'frontal')
%test('isreal', 'frontal')
%test('minus', 'frontal')
%test('mtimes', 'frontal')
%test('plus', 'frontal')
%test('reshape', 'frontal')
%test('size', 'frontal')
%test('sqrt', 'frontal')
%test('subsasgn', 'frontal')
%test('subsref', 'frontal')
%test('times', 'frontal')
%test('transpose', 'frontal')
%test('uminus', 'frontal')
%test('uplus', 'frontal')
%test('vertcat', 'frontal')

