function figure_round
n = 6;
figure
  %pp([0, 0], [0 1], 'o-r', ...
  %pp([], [], '.', ...
  pp(0, 0, '.k', ...
    'MaxValue',1, ...
    'CentreValue',0, ...
    'ThetaStartAngle',270, ...
    'ThetaDirection','cw', ...
    'AngleStep',45, ...
    'AngleLineWidth',1, ...
    'AngleAxisStyle','-', ...
    'AngleAxisColor',[1 1 1]*0.5, ...
    'RingLineWidth',1, ...
    'RingAxisStyle','-', ...
    'RingAxisColor',[1 1 1]*0.5, ...
    'MagMarkAngle',-(25-90), ...
    'RingTick',linspace(1, 0, n+1), ...
    'RingTickLabel',roundn(asind(1-linspace(1, 0, n+1)), 0) ...
  )
  axis equal
  hold on

