function varargout = mypp (azim_or_zen, val, m, l, c, valc, valo, varargin)
  if (nargin < 2) || isempty(val),  val = 1;  end
  if (nargin < 3) || isempty(m),  m = '.';  end
  if (nargin < 4) || isempty(l),  l = '-';  end
  if (nargin < 5) || isempty(c),  c = 'k';  end
  if (nargin < 6) || isempty(valc),  valc = 0;  end  % center
  if (nargin < 7) || isempty(valo),  valo = max(val);  end  % outer
  if isscalar(val),  val = repmat(val, size(azim_or_zen));  end
  if ischar(valc) && strcmpi(valc, 'min'),  valc = min(val);  end
  [varargout{1:nargout}] = pp (azim_or_zen*pi/180, val, ...
    'ThetaDirection','cw', ...
    'ThetaStartAngle',+270, ...
    ...%'MaxValue',temp1, ...
    'CentreValue',valc, ...
    'MaxValue',valo, ...
    'Marker',m, ...
    'LineStyle',l, ...
    'LineColor',c, ...
    'LineWidth',2, ...
    'CheckVoids','off', ...
    varargin{:} ...
  );
  axis equal
end
