function skyplot (elev, azim, s, varargin)
if (nargin < 3),  s = '-';  end

pp(azim*pi/180, cos(elev*pi/180), s, ...
  'ThetaDirection','cw', ...
  'ThetaStartAngle',+270, ...
  'MaxValue',1, ...
  'CentreValue',0, ...
  'RingStep',0.25, ...
  'RingTickLabel',...
    arrayfun(@(x) sprintf('%.0f^\\circ', x), acos(1:-0.25:0)'*180/pi, ...
      'UniformOutput',false), ...
  varargin{:} ...
)
axis equal

end